version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: cron_jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
      image: redis:latest
      container_name: redis-dev
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
